# Generated by Django 5.1.7 on 2025-07-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='method',
            field=models.CharField(choices=[('COD', 'Cash on delivery'), ('STRIPE', 'Stripe'), ('PAYPAL', 'Paypal'), ('CREDIT_CARD', 'Credit Card')], default='STRIPE', max_length=255),
        ),
    ]
