# Generated by Django 5.1.7 on 2025-08-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
