# Generated by Django 5.1.7 on 2025-07-25 05:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('user_registered', 'New User Registered'), ('user_profile_updated', 'User Profile Updated'), ('order_placed', 'Order Placed'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('order_returned', 'Order Returned'), ('support_reply', 'Support Team Replied'), ('user_message', 'New User Message'), ('system_alert', 'System Alert'), ('maintenance_notice', 'Scheduled Maintenance'), ('promo_offer', 'New Promotional Offer'), ('custom', 'Custom Notification')], max_length=55)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='dashboard_n_user_id_b572f4_idx'), models.Index(fields=['notification_type'], name='dashboard_n_notific_47e787_idx'), models.Index(fields=['created_at'], name='dashboard_n_created_526fd9_idx')],
            },
        ),
    ]
