# Generated by Django 5.1.7 on 2025-08-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_notification_content_type_notification_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
